### ISSUE TITLE
What are you using for a study guide?

### ISSUE THREAD

**Issue by Danathar** [1980is/rhcsa-9#1]
If you don’t mind me asking? What are you using for a study guide?

**Comment by bumipl** [comment]
Probably RHCSA9 course from Sander Van Vugt (oreill'y platform)

**Comment by Danathar** [comment]
> Probably RHCSA9 course from Sander Van Vugt (oreill'y platform)

Yea, that's what I ended up using, decent book thus far but man his copyeditor is terrible, I've found some rather obvious typos and errors.

**Comment by linux-ninja** [comment]
Sorry, did not notice your question.
I use a lot of stuff from Sander Van Vugt through oreilly.com.
I also read [Red Hat RHCSA 9 Cert Guide: EX200, Red Hat Enterprise Linux 9 Administration - Second Edition and a few other things.
